/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.foundvio.model;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.EntireEncrypted;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

import java.util.Date;

/**
 * Definition of ObjectType User.
 *
 * @since 2021-06-26
 */
@PrimaryKeys({"id"})
public final class User extends CloudDBZoneObject {
    private Integer id;

    @NotNull
    @DefaultValue(stringValue = "-")
    private String name;

    @NotNull
    @DefaultValue(stringValue = "-")
    private String email;

    @NotNull
    @DefaultValue(stringValue = "-")
    private String phone;

    @NotNull
    @DefaultValue(stringValue = "-")
    private String huaweiToken;

    public User() {
        super(User.class);
        this.name = "-";
        this.email = "-";
        this.phone = "-";
        this.huaweiToken = "-";
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getEmail() {
        return email;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getPhone() {
        return phone;
    }

    public void setHuaweiToken(String huaweiToken) {
        this.huaweiToken = huaweiToken;
    }

    public String getHuaweiToken() {
        return huaweiToken;
    }

}
